# Generated by Django 4.2.4 on 2024-10-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_gender_alter_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='city',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.RemoveField(
            model_name='student',
            name='zip_code',
        ),
    ]
