# Generated by Django 4.2.4 on 2024-03-29 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0003_alter_teacher_gender'),
        ('students', '0005_alter_student_gender_alter_student_phone'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Name of the subject', max_length=255, unique=True)),
                ('subject_code', models.CharField(help_text='Code of the subject (e.g., SUB001)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Subject code must be in the format SUB###', regex='^SUB\\d{3}$')])),
                ('subject_description', models.TextField(blank=True, help_text='Description of the subject', null=True)),
                ('weekday', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week when the subject is scheduled', max_length=20)),
                ('period_start_time', models.TimeField(help_text='Start time of the subject')),
                ('period_end_time', models.TimeField(help_text='End time of the subject')),
                ('class_room', models.CharField(choices=[('U101', 'U101'), ('U202', 'U202'), ('U104', 'U104'), ('U506', 'U506')], default='U101', help_text='Classroom where the subject is conducted', max_length=20)),
                ('class_period', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', help_text='Period number of the subject', max_length=2)),
                ('subject_faculty', models.ForeignKey(help_text='Faculty offering the subject', null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.department')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True, help_text='Date when the student registered for the subject')),
                ('student', models.ManyToManyField(help_text='Student registering for the subject', to='students.student')),
                ('subject', models.ForeignKey(help_text='Subject being registered by the student', on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
                ('teacher', models.ManyToManyField(help_text='Teacher assigned to the subject', null=True, to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Subject Registration',
                'verbose_name_plural': 'Subject Registrations',
                'ordering': ['registration_date'],
            },
        ),
    ]
