# Generated by Django 4.2.4 on 2024-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_gender'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectregistration',
            name='teacher',
            field=models.ManyToManyField(help_text='Teacher assigned to the subject', to='teachers.teacher'),
        ),
    ]
