# Generated by Django 4.2.4 on 2024-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subjectregistration_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(help_text='Code of the subject (e.g., SUB001)', max_length=255, unique=True),
        ),
    ]
