# Generated by Django 4.2.4 on 2024-03-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_gender'),
        ('subjects', '0003_alter_subject_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectregistration',
            name='teacher',
        ),
        migrations.AddField(
            model_name='subjectregistration',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher assigned to the subject', null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
    ]
