# Generated by Django 4.2.4 on 2024-03-31 10:34

import courses.subjects.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_gender_alter_student_phone'),
        ('subjects', '0004_remove_subjectregistration_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('assigment_type', models.CharField(choices=[('Text', 'Text'), ('File', 'File')], default='File', max_length=10, verbose_name='Type')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted Date')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('submission_count', models.PositiveIntegerField(default=0, verbose_name='Submission Count')),
                ('max_grade', models.PositiveIntegerField(default=100, verbose_name='Max Grade')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('reminder_email_sent', models.BooleanField(default=False, verbose_name='Reminder Email Sent')),
                ('deadline_email_sent', models.BooleanField(default=False, verbose_name='Deadline Email Sent')),
                ('create_notification_start', models.BooleanField(default=False, verbose_name='Create Notification Start')),
                ('create_notification_end', models.BooleanField(default=False, verbose_name='Create Notification End')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='Course')),
                ('students', models.ManyToManyField(blank=True, related_name='assigned_assignments', to='students.student', verbose_name='Students')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=courses.subjects.models.get_assignment_file_path, verbose_name='File')),
            ],
            options={
                'verbose_name': 'Assignment File',
                'verbose_name_plural': 'Assignment Files',
            },
        ),
        migrations.CreateModel(
            name='TextAssigemntQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question for the assignment')),
            ],
            options={
                'verbose_name': 'Text Assignment Question',
                'verbose_name_plural': 'Text Assignment Questions',
            },
        ),
        migrations.CreateModel(
            name='TextQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.textassigemntquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Text Question Answer',
                'verbose_name_plural': 'Text Question Answers',
            },
        ),
        migrations.CreateModel(
            name='TextSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Is Submitted')),
                ('student_answer_file', models.FileField(blank=True, null=True, upload_to='student_answer_files', verbose_name='Student Answer File')),
                ('is_graded', models.BooleanField(default=False, verbose_name='Is Graded')),
                ('grade', models.PositiveIntegerField(default=0, verbose_name='Grade')),
                ('answers', models.ManyToManyField(to='subjects.textquestionanswer', verbose_name='Answers')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_submissions', to='subjects.assignment', verbose_name='Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Text Submission',
                'verbose_name_plural': 'Text Submissions',
            },
        ),
        migrations.CreateModel(
            name='FileSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_submited', models.BooleanField(default=False)),
                ('is_graded', models.BooleanField(default=False)),
                ('grade', models.PositiveIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_submissions', to='subjects.assignment')),
                ('assignment_submission_file', models.ManyToManyField(related_name='assignments', to='subjects.assignmentfile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'verbose_name': 'File Submission',
                'verbose_name_plural': 'File Submissions',
            },
        ),
    ]
