# Generated by Django 4.2.4 on 2024-04-01 00:32

import courses.subjects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_assignment_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to=courses.subjects.models.UploadToPathAndRename('course_materials'))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Course Material',
                'verbose_name_plural': 'Course Materials',
            },
        ),
    ]
