# Generated by Django 4.2.4 on 2024-04-01 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_coursemateriales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcement_file')),
            ],
            options={
                'verbose_name': 'Announcement File',
                'verbose_name_plural': 'Announcement Files',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=255)),
                ('announcement_description', models.TextField()),
                ('announcement_date', models.DateTimeField(auto_now_add=True)),
                ('announcement_last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('announcement_file_url', models.ManyToManyField(blank=True, related_name='announcements', to='subjects.announcementfile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
