# Generated by Django 4.2.4 on 2024-04-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_assignment_is_visible_alter_assignmentfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textsubmission',
            name='student_answer_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Student Answer File'),
        ),
    ]
