# Generated by Django 4.2.4 on 2024-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_alter_textsubmission_student_answer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentfile',
            name='file',
            field=models.FileField(max_length=255, upload_to='', verbose_name='File'),
        ),
    ]
