version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api
    ports:
      - "8001:8001"
    # command: gunicorn university.wsgi:application --bind 0.0.0.0:8001
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./api:/app/api
    depends_on:
      - db
      - redis
      - celery
  celery:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./api:/app/api
    depends_on:
      - db
      - redis
    command: celery -A university worker --loglevel=info
  celery-beat:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./api:/app/api
    depends_on:
      - db
      - redis
      - celery
    command: celery -A university beat --loglevel=info
    
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lmsdatabase
  
  redis:
    image: redis:3.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/client
    depends_on:
      - api
      
volumes:
  postgres_data:
  redis_data: