version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: api
    ports:
      - "8001:8001"
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./api:/app/api
