version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=lmsdatabase
      - DB_USER=root
      - DB_PASSWORD=root
    volumes:
      - ./backend:/app/api  

  database:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: database
    image: postgres:latest
    environment:
      POSTGRES_DB: lmsdatabase
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: