services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: api
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/srv/app
      - ./var/log/api:/var/log/api
      - static_volume:/api/static
      - media_volume:/api/media
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: school_db
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_IMAP_USERNAME: ${EMAIL_IMAP_USERNAME}
      EMAIL_IMAP_PASSWORD: ${EMAIL_IMAP_PASSWORD}
      DEVELOPMENT_MODE: ${DEVELOPMENT_MODE}

    networks:
      - school_app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "80:80"

    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/client/build:/usr/share/nginx/html
      - ./var/log/web:/var/log/nginx/
    
    networks:
      - school_app


volumes:
  static_volume: {} 
  media_volume: {}

networks:
  school_app:
    driver: bridge
