services:
  celery:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./services/api:/app/api
    depends_on:
      - redis
    command: celery -A config worker --loglevel=info

  celery-beat:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./services/api:/app/api
    depends_on:
      - redis
      - celery
    command: celery -A config beat --loglevel=info

  redis:
    image: redis:3.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
