services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: api
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/srv/app
      - static_volume:/api/static
      - media_volume:/api/media
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: school_db
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_IMAP_USERNAME: ${EMAIL_IMAP_USERNAME}
      EMAIL_IMAP_PASSWORD: ${EMAIL_IMAP_PASSWORD}
      DEVELOPMENT_MODE: ${DEVELOPMENT_MODE}

    networks:
      - school_app

volumes:
  static_volume: {} 
  media_volume: {}

networks:
  school_app:
    driver: bridge
