version: '3.8'



services:
  django:
    build: ./backend

    ports:
      - "8000:8000"
    depends_on:
      - flask

  flask:
    build: ./websocket
    ports:
      - "5000:5000"

  react:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - django
