version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn university.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/client 
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
