
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - celery_network

  celery:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./services/api:/app/api
    depends_on:
      - redis
    command: poetry run celery -A config.celery worker --loglevel=info
    env_file:
      - services/api/.env
    networks:
      - celery_network

  celery-beat:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./services/api:/app/api
    depends_on:
      - redis
      - celery
    command: poetry run celery -A config.celery beat --loglevel=info
    env_file:
      - services/api/.env
    networks:
      - celery_network

volumes:
  redis_data:

networks:
  celery_network:
