version: '3.8'

services:
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - gcp-creds:/creds
      - ./api:/api
    working_dir: /app/api
    environment:
      - CLOUDSDK_CONFIG=/creds
  
volumes:
  gcp-creds:
