services:
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cocqYp-nodma7-cyszag?+`***@

    ports:
    # build only for local
     - "127.0.0.1:5432:5432"


    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - school_app
volumes:
  db_data:

networks:
  school_app:
