services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
      target: api
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/srv/app
      - ./services/api/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./var/log:/srv/app/var/log/api
      - ./var/log/supervisor:/var/log/django_services/supervisor
      - static_volume:/api/static
      - media_volume:/api/media
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: school_db
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_IMAP_USERNAME: ${EMAIL_IMAP_USERNAME}
      EMAIL_IMAP_PASSWORD: ${EMAIL_IMAP_PASSWORD}
      DEVELOPMENT_MODE: ${DEVELOPMENT_MODE}
    networks:
      - school_app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/client/build:/usr/share/nginx/html
      - ./services/api/media:/usr/share/nginx/html/media
      - ./var/log/web:/var/log/nginx/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot


    networks:
      - school_app

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal -d bhuj-le.tech --agree-tos --staging --email yabindra2057@gmail.com --non-interactive


volumes:
  static_volume: {} 
  media_volume: {}

networks:
  school_app:
    driver: bridge
