version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: LMS
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/Django
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
