# Generated by Django 4.2.4 on 2023-11-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0019_alter_textanswer_question_and_more'),
        ('teacher', '0034_alter_teacher_gender'),
        ('student', '0038_alter_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_grade', models.PositiveIntegerField(default=100)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
                ('student', models.ManyToManyField(blank=True, null=True, related_name='exams', to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('True/False', 'True/False'), ('Short Answer', 'Short Answer'), ('Long Answer', 'Long Answer')], default='MCQ', max_length=20)),
                ('max_grade', models.PositiveIntegerField(default=100)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question_number', models.PositiveIntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
