# Generated by Django 4.2.4 on 2023-11-16 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_longanswerquestion_mcqquestion_shortanswerquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longanswerquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='mcqquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='shortanswerquestion',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='question_ptr',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='LongAnswerQuestion',
        ),
        migrations.DeleteModel(
            name='MCQQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='ShortAnswerQuestion',
        ),
        migrations.DeleteModel(
            name='TrueFalseQuestion',
        ),
    ]
