# Generated by Django 4.2.4 on 2023-11-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcqquestion',
            old_name='choice',
            new_name='choice_answer',
        ),
    ]
