# Generated by Django 4.2.4 on 2023-11-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_rename_choice_mcqquestion_choice_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcqquestion',
            name='choice_answer',
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='choice_answer',
            field=models.ManyToManyField(blank=True, null=True, related_name='mcq_question', to='exam.choicemodel'),
        ),
    ]
