# Generated by Django 4.2.4 on 2023-11-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_mcqquestion_choice_answer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQQuestion',
        ),
    ]
