# Generated by Django 4.2.4 on 2023-11-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_delete_mcqquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceModel',
        ),
    ]
