# Generated by Django 4.2.4 on 2023-12-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_alter_student_gender'),
        ('exam', '0008_delete_choicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('submitted_datetime', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('short_answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.shortanswerquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='LongAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('submitted_datetime', models.DateTimeField(auto_now=True)),
                ('long_answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.longanswerquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
