# Generated by Django 4.2.4 on 2023-12-11 04:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0053_alter_student_gender'),
        ('exam', '0009_shortanswermodel_longanswermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortAnswerModel',
            new_name='LongAnswer',
        ),
        migrations.RenameModel(
            old_name='LongAnswerModel',
            new_name='ShortAnswer',
        ),
        migrations.RemoveField(
            model_name='longanswer',
            name='short_answer_question',
        ),
        migrations.RemoveField(
            model_name='shortanswer',
            name='long_answer_question',
        ),
        migrations.AddField(
            model_name='longanswer',
            name='long_answer_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.longanswerquestion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortanswer',
            name='short_answer_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.shortanswerquestion'),
            preserve_default=False,
        ),
    ]
