# Generated by Django 4.2.4 on 2023-12-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0053_alter_student_gender'),
        ('exam', '0010_rename_shortanswermodel_longanswer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LongAnswer',
            new_name='LongAnswerModel',
        ),
        migrations.RenameModel(
            old_name='ShortAnswer',
            new_name='ShortAnswerModel',
        ),
    ]
