# Generated by Django 4.2.4 on 2023-12-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_rename_longanswer_longanswermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longanswermodel',
            name='long_answer_question',
        ),
        migrations.RemoveField(
            model_name='longanswermodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='longanswermodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='longanswerquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='longanswerquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='shortanswermodel',
            name='question',
        ),
        migrations.RemoveField(
            model_name='shortanswermodel',
            name='short_answer_question',
        ),
        migrations.RemoveField(
            model_name='shortanswermodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='shortanswerquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='shortanswerquestion',
            name='question',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='LongAnswerModel',
        ),
        migrations.DeleteModel(
            name='LongAnswerQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='ShortAnswerModel',
        ),
        migrations.DeleteModel(
            name='ShortAnswerQuestion',
        ),
    ]
