# Generated by Django 4.2.4 on 2023-12-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_active',
        ),
    ]
