# Generated by Django 4.2.4 on 2024-01-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0064_alter_student_gender'),
        ('exam', '0014_remove_exam_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ManyToManyField(related_name='exams', to='student.student'),
        ),
        migrations.AlterField(
            model_name='longanswerquestion',
            name='question',
            field=models.ManyToManyField(related_name='long_answer_question', to='exam.question'),
        ),
        migrations.AlterField(
            model_name='shortanswerquestion',
            name='question',
            field=models.ManyToManyField(related_name='short_answer_question', to='exam.question'),
        ),
    ]
