# Generated by Django 4.2.4 on 2024-01-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0065_alter_student_gender'),
        ('exam', '0015_alter_exam_student_alter_longanswerquestion_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='exams', to='student.student'),
        ),
        migrations.AlterField(
            model_name='longanswerquestion',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='long_answer_question', to='exam.question'),
        ),
        migrations.AlterField(
            model_name='shortanswerquestion',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='short_answer_question', to='exam.question'),
        ),
    ]
