from django.urls import path

from.views import *

urlpatterns = [
    path('assignment/<int:id>/', updateAssigmentvisibility, name='updateAssigmentvisibility'),
    path('create_syllabus/<int:id>/', createSyllabus, name='createSyllabus'),
    path('update_course/<int:id>/', updateCourse, name='update_course'),
    path('get_course_details/<int:id>/', getCourseDetails, name='getCourseDetails'),
    path('syllabus_update/<int:id>/', updateSyyllabus, name='syllabus'),
    path('syllabus/<str:subject_code>/', syllabusByCourse, name='syllabus'),
    path('create_enroll_subject/<str:username>/', createEnrollSubject, name='create_enroll_subject'),
    path('get_subject_enroll/<str:username>/', getSubjectEnroll, name='get_subject_enroll'),
    path('create_course/', createCourse, name='create_course'),
    path('delete_course/<str:id>/<str:username>/', deleteCourse, name='delete_course'),
    path('delete_department/<int:id>/<str:username>/', deleteDepartment, name='delete_department'),
    path('add_department/<str:username>/', addDepartment, name='add_department'),
    path('update_department/<str:username>/<int:id>/', updateDepartment, name='update_department'),
    path('get_announcement_by_student/', getAnnouncementByStudent, name='get_announcement_by_student'),
    path('update_announcement/<int:id>/', updateAnnouncement, name='update_announcement'),
    path('delete_announcement/<int:id>/', deleteAnnouncement, name='delete_announcement'),
    path('handle_active_change_announcement/<int:id>/', handle_active_change_announcement, name='handle_active_change_announcement'),
    path('get_announcement_by_subject/<int:subject_code>/', getAnnouncementBySubject, name='get_announcement_by_subject'),
    path('get_announcement_by_subject_student/<int:subject_code>/', getAnnouncementBySubjectStudent, name='get_announcement_by_subject_student'),
    path('AddAnnouncement/', addAnnouncement, name='AddAnnouncement'),
    path('delete_file/<int:id>/', deleteFile, name='delete_file'),
    path('get_attendance_by_student_subject/<int:subjectID>/', getAttendanceByStudentSubject, name='get_attendance_by_student_subject'),
    path('update_submission/', updateSubmission, name='update_submission'),
    path('delete_assigemnt_question/<int:id>/', deleteAssigemntQuestion, name='delete_assigemnt_question'),
    path('upadteAssigemnt/', upadteAssigemnt, name='upadteAssigemnt'),
    path('get_attendance_by_student/<int:student_id>/', getAttendanceByStudent, name='get_attendance_by_student'),
    path('get_student_list_by_subject_id/<int:subject_code>/', getStudentListBySubjectId, name='get_student_list_by_subject_id'),
    path('create_attdenace_and_add_student/', createAttdenaceAndAddStudent, name='create_attdenace_and_add_student'),
    path('get_attendance_by_subject/<int:subject_code>/', getAttendanceBySubject, name='get_attendance_by_subject'),
    path('create_attendance/', createAttendance, name='create_attendance'),
    path('mark_attendance/', markAttendance, name='mark_attendance'),
    path('department_list/', departmentList, name='department_list'), 
    path('file_assigment/', fileAssigment, name='file_assigment'), 
    path('text_assignment/', textAssignment, name='text_assigment'),
    path('admin/',admincourseList ,name='admincourse_list'), 
    path('create_assigment/', createAssigment, name='create_assigment'),
    path('assigment_detalis/<int:id>/', assignmentDetails, name='assigment_detalis'),
    path('student_assignment_details/<int:id>/', studentAssignmentDetails, name='student_assignment_details'),
    path('get_file/', getFile, name='get_file'),
    path('<str:subject_code>/<int:studentID>/', courseDetailsStudent, name='course_details_student'),
    path('<str:subject_code>/', courseDetails, name='course_details'),
    path('get_all_assignment/<str:username>/', getAllAssignment, name='get_all_assignment'), 
    path('get_active_assigemnt/<str:username>/', getActiveAssigemnt, name='get_active_assigemnt'), 
    path('get_past_assigemnt/<str:username>/', getPastAssigemnt, name='get_past_assigemnt'), 
    path('get_future_assigemnt/<str:username>/', getFutureAssigemnt, name='get_future_assigemnt'),

]