# Generated by Django 4.2.4 on 2023-10-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_userprofile_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
        migrations.DeleteModel(
            name='TenantUser',
        ),
    ]
