# Generated by Django 4.2.4 on 2023-11-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_delete_university_delete_tenantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='defult.png', null=True, upload_to='user_profile/'),
        ),
    ]
