# Generated by Django 4.2.4 on 2023-11-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/user_profile/defult.png', null=True, upload_to='user_profile/'),
        ),
    ]
