# Generated by Django 4.2.4 on 2024-02-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_applicationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsettings',
            name='isEmailNotification',
            field=models.BooleanField(default=False),
        ),
    ]
