# Generated by Django 4.2.4 on 2024-03-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_applicationsettings_isemailnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
    ]
