# Generated by Django 4.2.4 on 2024-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='user_profile/defutl_user.png', null=True, upload_to='user_profile/'),
        ),
    ]
