# Generated by Django 4.2.4 on 2023-10-13 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtimeapi', '0002_frendrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrendRequest',
            new_name='FriendRequest',
        ),
    ]
