# Generated by Django 4.2.4 on 2023-10-16 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('realtimeapi', '0003_rename_frendrequest_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocketID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_id', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_socket_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
