# Generated by Django 4.2.4 on 2023-10-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeapi', '0005_group_admin_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
