# Generated by Django 4.2.4 on 2023-10-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeapi', '0006_friendrequest_is_delivered_friendrequest_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
