# Generated by Django 4.2.4 on 2023-12-27 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeapi', '0009_comment_imagestore_like_post_videostore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images'),
        ),
        migrations.AddField(
            model_name='group',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 27, 2, 10, 51, 68430, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
