# Generated by Django 4.2.4 on 2023-12-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeapi', '0010_group_group_image_group_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
