# Generated by Django 4.2.4 on 2023-12-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeapi', '0011_message_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image_data',
            field=models.ImageField(blank=True, null=True, upload_to='message_image'),
        ),
    ]
