# Generated by Django 4.2.4 on 2023-08-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendermodel',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
