# Generated by Django 4.2.4 on 2023-10-31 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_calendermodel_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendermodel',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='calendermodel',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='calendermodel',
            name='time',
        ),
    ]
