# Generated by Django 4.2.4 on 2023-11-06 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_assignmentnotificationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentnotificationmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='assignmentnotificationmodel',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
