# Generated by Django 4.2.4 on 2023-11-20 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_remove_assignmentnotificationmodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendermodel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='calendermodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='calendermodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='calendermodel',
            name='user',
        ),
    ]
