# Generated by Django 4.2.4 on 2023-11-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_remove_calendermodel_color_remove_calendermodel_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalenderModel',
        ),
    ]
