# Generated by Django 4.2.4 on 2023-12-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0009_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_type',
            field=models.CharField(choices=[('private', 'private'), ('shared', 'shared')], default='private', max_length=20),
        ),
    ]
