# Generated by Django 4.2.4 on 2024-01-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_notificationmodel_usernotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
