# Generated by Django 4.2.4 on 2024-02-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_notes_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendermodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
