# Generated by Django 4.2.4 on 2024-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_alter_calendermodel_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendermodel',
            name='time',
        ),
        migrations.AlterField(
            model_name='calendermodel',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendermodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
