# Generated by Django 4.2.4 on 2024-03-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0016_remove_calendermodel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendermodel',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendermodel',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendermodel',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendermodel',
            name='start_date',
            field=models.DateField(),
        ),
    ]
