# Generated by Django 4.2.4 on 2024-03-19 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_assignment_create_notification_end_and_more'),
        ('notification', '0017_calendermodel_end_time_calendermodel_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendermodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
    ]
