# Generated by Django 4.2.4 on 2024-03-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0019_alter_calendermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendermodel',
            name='is_class_cancellation',
            field=models.BooleanField(default=False),
        ),
    ]
