# Generated by Django 4.2.4 on 2024-03-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='TeacherID',
            new_name='teacher_id',
        ),
    ]
