# Generated by Django 4.2.4 on 2023-08-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teacher', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='subjectenroll',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='subjectenroll',
            name='student',
            field=models.ManyToManyField(to='student.student'),
        ),
        migrations.AddField(
            model_name='subjectenroll',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_submissions', to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='filetextsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_text_submissions', to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='filetextsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_submissions', to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='student.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='assignments', to='student.student'),
        ),
    ]
