# Generated by Django 4.2.4 on 2023-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Department_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='Department_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
