# Generated by Django 4.2.4 on 2023-08-25 03:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_subject_subject_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_posted_time',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_start_time',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
