# Generated by Django 4.2.4 on 2023-10-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursemateriales_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_submission')),
            ],
        ),
        migrations.RemoveField(
            model_name='filesubmission',
            name='assignment_submission_file',
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='assignment_submission_file',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='courses.assignmentfile'),
        ),
    ]
