# Generated by Django 4.2.4 on 2023-11-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_assignmentfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
