# Generated by Django 4.2.4 on 2023-11-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_alter_student_gender'),
        ('courses', '0009_assignment_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('isPresent', models.BooleanField(default=False)),
                ('attendance_code', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
                ('student', models.ManyToManyField(blank=True, null=True, to='student.student')),
            ],
            options={
                'abstract': False,
                'unique_together': {('course', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='QrcodeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('isPresent', models.BooleanField(default=False)),
                ('qrcode_image', models.ImageField(blank=True, null=True, upload_to='qr_code')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
                ('student', models.ManyToManyField(blank=True, null=True, to='student.student')),
            ],
            options={
                'abstract': False,
                'unique_together': {('course', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.RemoveField(
            model_name='filetextsubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='filetextsubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='imagesubmission',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='FileTextSubmission',
        ),
        migrations.DeleteModel(
            name='ImageSubmission',
        ),
    ]
