# Generated by Django 4.2.4 on 2023-11-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_codeattendance_qrcodeattendance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrcodeattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='qrcodeattendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='qrcodeattendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='CodeAttendance',
        ),
        migrations.DeleteModel(
            name='QrcodeAttendance',
        ),
    ]
