# Generated by Django 4.2.4 on 2023-11-07 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_qrcodeattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
