# Generated by Django 4.2.4 on 2023-11-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_textassigemntquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textassigemntquestion',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
