# Generated by Django 4.2.4 on 2023-11-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_textassigemntquestion_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textassigemntquestion',
            name='assignment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='text_question',
            field=models.ManyToManyField(blank=True, null=True, to='courses.textassigemntquestion'),
        ),
    ]
