# Generated by Django 4.2.4 on 2023-11-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_textassigemntquestion_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('File', 'File'), ('Text', 'Text')], default='File', max_length=20),
        ),
    ]
