# Generated by Django 4.2.4 on 2023-11-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_assignment_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textsubmission',
            name='assignment_submission_text',
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.textassigemntquestion')),
                ('text_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.textsubmission')),
            ],
        ),
    ]
