# Generated by Django 4.2.4 on 2023-11-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_textsubmission_assignment_submission_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textanswer',
            name='text_submission',
        ),
        migrations.AddField(
            model_name='textsubmission',
            name='answer',
            field=models.ManyToManyField(blank=True, to='courses.textanswer'),
        ),
    ]
