# Generated by Django 4.2.4 on 2023-11-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_textanswer_text_submission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.textassigemntquestion'),
        ),
        migrations.AlterField(
            model_name='textsubmission',
            name='answer',
            field=models.ManyToManyField(to='courses.textanswer'),
        ),
    ]
