# Generated by Django 4.2.4 on 2023-11-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendace_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
