# Generated by Django 4.2.4 on 2023-11-28 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_attendance_attendace_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject_enroll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.subjectenroll'),
            preserve_default=False,
        ),
    ]
