# Generated by Django 4.2.4 on 2023-11-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0048_alter_student_gender'),
        ('courses', '0023_alter_attendance_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendace_code',
            new_name='attendance_code',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.CreateModel(
            name='StudentAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='students_attended',
            field=models.ManyToManyField(to='courses.studentattended'),
        ),
    ]
