# Generated by Django 4.2.4 on 2023-11-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_rename_attendace_code_attendance_attendance_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='students_attended',
            field=models.ManyToManyField(blank=True, null=True, to='courses.studentattended'),
        ),
    ]
