# Generated by Django 4.2.4 on 2023-11-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_attendance_students_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
