# Generated by Django 4.2.4 on 2023-11-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_attendance_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattended',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
