# Generated by Django 4.2.4 on 2023-11-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_studentattended_attendance_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_code',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='students_attended',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject_enroll',
        ),
        migrations.RemoveField(
            model_name='studentattended',
            name='attendance_code',
        ),
        migrations.RemoveField(
            model_name='studentattended',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='studentattended',
            name='student',
        ),
    ]
