# Generated by Django 4.2.4 on 2023-11-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_attendance_attendance_code_attendance_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattended',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='StudentAttended',
        ),
    ]
