# Generated by Django 4.2.4 on 2023-11-29 03:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0051_alter_student_gender'),
        ('courses', '0030_remove_studentattended_student_delete_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('attendance_code', models.CharField(blank=True, max_length=10, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attendance_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
                ('students_attended', models.ManyToManyField(blank=True, null=True, to='courses.studentattended')),
                ('subject_enroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subjectenroll')),
            ],
        ),
    ]
