# Generated by Django 4.2.4 on 2023-12-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsubmission',
            name='student_asnwer_file',
            field=models.FileField(blank=True, null=True, upload_to='student_asnwer_file'),
        ),
    ]
