# Generated by Django 4.2.4 on 2023-12-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_textsubmission_student_asnwer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='textsubmission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
