# Generated by Django 4.2.4 on 2023-12-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_filesubmission_is_graded_textsubmission_is_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textsubmission',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
