# Generated by Django 4.2.4 on 2023-12-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_filesubmission_grade_textsubmission_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_active',
        ),
    ]
