# Generated by Django 4.2.4 on 2024-01-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0064_alter_student_gender'),
        ('courses', '0036_remove_assignment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ManyToManyField(related_name='assignments', to='student.student'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='text_question',
            field=models.ManyToManyField(to='courses.textassigemntquestion'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='students_attended',
            field=models.ManyToManyField(to='courses.studentattended'),
        ),
        migrations.AlterField(
            model_name='filesubmission',
            name='assignment_submission_file',
            field=models.ManyToManyField(related_name='assignments', to='courses.assignmentfile'),
        ),
    ]
