# Generated by Django 4.2.4 on 2024-01-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0065_alter_student_gender'),
        ('courses', '0037_alter_assignment_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='student.student'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='text_question',
            field=models.ManyToManyField(blank=True, to='courses.textassigemntquestion'),
        ),
    ]
