# Generated by Django 4.2.4 on 2024-01-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_alter_assignment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattended',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='students_attended',
            field=models.ManyToManyField(related_name='attendances', to='courses.studentattended'),
        ),
    ]
