# Generated by Django 4.2.4 on 2024-01-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='announcement_file',
            field=models.FileField(blank=True, null=True, upload_to='announcement_file'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
