# Generated by Django 4.2.4 on 2024-01-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_announcement_announcement_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcement_file')),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='announcement_file',
        ),
        migrations.AddField(
            model_name='announcement',
            name='announcement_file_url',
            field=models.ManyToManyField(related_name='announcements', to='courses.announcementfile'),
        ),
    ]
