# Generated by Django 4.2.4 on 2024-01-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_announcementfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_file_url',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='courses.announcementfile'),
        ),
    ]
