# Generated by Django 4.2.4 on 2024-01-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_alter_announcement_announcement_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_room',
            field=models.CharField(choices=[('U101', 'U101'), ('U202', 'U202'), ('U104', 'U104'), ('U506', 'U506')], default='U101', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
