# Generated by Django 4.2.4 on 2024-02-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_alter_subject_class_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Department_code',
            new_name='departmentCode',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Department_name',
            new_name='departmentName',
        ),
    ]
