# Generated by Django 4.2.4 on 2024-02-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_rename_department_code_department_departmentcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmentCode',
            new_name='Department_code',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='departmentName',
            new_name='Department_name',
        ),
    ]
