# Generated by Django 4.2.4 on 2024-03-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_syllabussection_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_actived',
            field=models.BooleanField(default=True),
        ),
    ]
