# Generated by Django 4.2.4 on 2024-03-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_assignment_is_actived'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
