# Generated by Django 4.2.4 on 2024-03-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_assignment_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='is_actived',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
