# Generated by Django 4.2.4 on 2024-03-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_rename_is_actived_assignment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='create_notification_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='create_notification_start',
            field=models.BooleanField(default=False),
        ),
    ]
