# Generated by Django 4.2.4 on 2024-04-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_alter_student_gender_alter_student_phone'),
        ('subjects', '0010_assignment_is_visible_alter_assignmentfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('attendance_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('attendance_code', models.CharField(blank=True, max_length=10, null=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='students_attended',
            field=models.ManyToManyField(related_name='attendances', to='attendance.studentattended'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject_enroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subjectregistration'),
        ),
    ]
