# Generated by Django 4.2.4 on 2023-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
