# Generated by Django 4.2.4 on 2023-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_alter_folder_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
