# Generated by Django 4.2.4 on 2023-10-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0006_alter_file_user_alter_folder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
