# Generated by Django 4.2.4 on 2024-01-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0070_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'gender'), ('Female', 'Female')], max_length=20),
        ),
    ]
