# Generated by Django 4.2.4 on 2023-08-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherID', models.CharField(default=0, max_length=255, unique=True)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
