# Generated by Django 4.2.4 on 2024-10-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_notification_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
