# Generated by Django 4.2.4 on 2024-10-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_notetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetag',
            name='name',
            field=models.CharField(default='University', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
