# Generated by Django 4.2.4 on 2024-10-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_calendarevent_is_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
