# Generated by Django 4.2.4 on 2024-10-29 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_notetag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notetag',
            name='notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='common.notetag', verbose_name='Tag'),
        ),
    ]
