# Generated by Django 4.2.4 on 2024-10-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_notetag_notes_notes_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tag',
            field=models.CharField(blank=True, default='University', max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.DeleteModel(
            name='NoteTag',
        ),
    ]
