# Generated by Django 4.2.4 on 2024-10-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_calendarevent_reminder_time'),
        ('common', '0007_alter_notes_tag_delete_notetag'),
    ]

    operations = [
    ]
