# Generated by Django 4.2.4 on 2023-09-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('input_description', models.TextField()),
                ('output_description', models.TextField()),
                ('example_input', models.TextField()),
                ('example_output', models.TextField()),
                ('iscomplate', models.BooleanField(default=False)),
            ],
        ),
    ]
