# Generated by Django 4.2.4 on 2023-09-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeproblem',
            old_name='example_input',
            new_name='hit',
        ),
        migrations.RemoveField(
            model_name='codeproblem',
            name='example_output',
        ),
        migrations.RemoveField(
            model_name='codeproblem',
            name='input_description',
        ),
        migrations.RemoveField(
            model_name='codeproblem',
            name='output_description',
        ),
    ]
