# Generated by Django 4.2.4 on 2023-09-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editer', '0002_rename_example_input_codeproblem_hit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeproblem',
            old_name='hit',
            new_name='hint',
        ),
    ]
