# Generated by Django 4.2.4 on 2023-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editer', '0003_rename_hit_codeproblem_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='excepted_answere',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
