# Generated by Django 4.2.4 on 2023-10-01 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editer', '0006_alter_codeproblem_excepted_answere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeproblem',
            old_name='excepted_answere',
            new_name='excepted_answere_descriotion',
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='exacty_answer',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProblemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iscomplate', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editer.codeproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
