# Generated by Django 4.2.4 on 2023-10-02 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editer', '0007_rename_excepted_answere_codeproblem_excepted_answere_descriotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='exactped_code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
