# Generated by Django 4.2.4 on 2023-10-20 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editer', '0009_userproblemanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='test_case',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
