on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Change directory to backend
      run: cd ${{ github.workspace }}/backend
      if: ${{ success() }}
      continue-on-error: true

    - name: Confirm current directory
      run: pwd


    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
      if: ${{ success() }}
      continue-on-error: true

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      if: ${{ success() }}
      continue-on-error: true

    - name: Run Tests
      run: |
        pytest
      if: ${{ success() }}
      continue-on-error: true
