      name: Django CI/CD
      on:
        push:
          branches:
            - main
        pull_request:
          branches:
            - main
      
      jobs:
        build:
          runs-on: ubuntu-latest

          env:
            SECRET_KEY: django-insecure-324-f+674e6s0(ng9$qzu9j)=44xom(vtsn#o+11_#7*e!az$0
            DEVELOPMENT_MODE: "False"
          defaults:
            run:
              working-directory: backend

          services:
            postgres:
              image: postgres:latest
              env:
                POSTGRES_USER: root
                POSTGRES_PASSWORD: root
                POSTGRES_DB: lmsdatabase
                name: lmsdatabase
              ports:
                - 5432:5432
              options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
          steps:
          - name: Checkout code
            uses: actions/checkout@v2
      
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.11
      
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      
          - name: Set up test database
            run: |
              python manage.py migrate --noinput
      
              
          - name: Run tests
            run: pytest
      
        deploy:
          name: Deploy to Google Cloud
          runs-on: ubuntu-latest
          steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.11
          
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Connect to google cloud
            uses: google-github-actions/auth@v0
            with:
              project_id: 	windy-pier-380508
              service_account_key: ${{ secrets.GCP_SA_KEY }}
              export_default_credentials: true

          - name: Gather static files
            run: python manage.py collectstatic --noinput

          - name: run migrations
            run: python manage.py migrate --noinput

          - name: Deploy to App Engine
            id: deploy
            uses: google-github-actions/deploy-appengine@v0
            with:
              deployable: app.yaml
              version: v1
              project_id: windy-pier-380508
              credentials: ${{ secrets.GCP_SA_KEY }}