name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    

    steps:
    - uses: actions/checkout@v3
    - name: Docker build
      run: |
        docker-compose build
    - name: Docker run
      run: |
        docker-compose up -d
    - name: Wait for services
      run: |
        sleep 10
    - name: Run tests
      run: |
        docker-compose exec backend pytest
    - name: Docker stop
      run: |
        docker-compose down
        
