name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.7]

    steps:
    - uses: actions/checkout@v3

    # Download and set up Python 3.11.7
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        echo "Downloading Python ${PYTHON_VERSION}..."
        curl -sSLO https://github.com/actions/python-versions/releases/download/${PYTHON_VERSION}/python-${PYTHON_VERSION}-linux-22.04-x64.tar.gz
        echo "Extracting Python ${PYTHON_VERSION}..."
        tar -xzf python-${PYTHON_VERSION}-linux-22.04-x64.tar.gz
        export PATH="$PWD/$(basename -s .tar.gz python-${PYTHON_VERSION}-linux-22.04-x64)/bin:$PATH"
        python -m pip install --upgrade pip

    # Install dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Run tests
    - name: Run Tests
      run: |
        pytest
