      name: Django CI/CD

      on:
        push:
          branches:
            - main
        pull_request:
          branches:
            - main
      
      jobs:
        build:
          runs-on: ubuntu-latest
          defaults:
            run:
              working-directory: backend
              
          services:
            postgres:
              image: postgres:latest
              env:
                POSTGRES_USER: root
                POSTGRES_PASSWORD: root
                POSTGRES_DB: lmsdatabase
                name: lmsdatabase
              ports:
                - 5432:5432
              options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      
          steps:
          - name: Checkout code
            uses: actions/checkout@v2
      
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.11
      
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      
          - name: Set up test database
            run: |
              python manage.py migrate --noinput
      
          - name: Run tests
            run: pytest
      
        deploy:
          needs: build
          runs-on: ubuntu-latest
      
          steps:
          - name: Checkout code
            uses: actions/checkout@v2
      
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.11
      
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
      