on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Change directory to backend
      run: cd schoollms/backend
      working-directory: ${{ github.workspace }}/schoollms/backend
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ github.workspace }}/schoollms/backend
    - name: Run Tests
      run: |
        pytest
      working-directory: ${{ github.workspace }}/schoollms/backend
