# Generated by Django 4.2.4 on 2024-03-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_assignment_assignmentfile_textassigemntquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='subjects.textassigemntquestion', verbose_name='Questions'),
        ),
    ]
