# Generated by Django 4.2.4 on 2024-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_syllabusitem_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='assignmentfile',
            name='file',
            field=models.FileField(upload_to='assignments/', verbose_name='File'),
        ),
    ]
